.DELETE_ON_ERROR:
.PHONY: all validate validatexml validatexhtml clean

UARCHRNG:=schemata/uarch.rng
RELAXNG:=schemata/processorzoo.rng
XML:=$(wildcard *.xml)
LISTS:=$(addprefix generated/,isas.rng uarches.rng)
UARCHXML:=$(wildcard uarches/*.xml)
XHTML:=$(addprefix generated/,processorzoo.html)

all: validate

validate: validatexml validatexhtml

validatexhtml: $(XHTML)

validatexml: $(UARCHRNG) $(RELAXNG) $(XML) $(LISTS)
	for i in $(XML) ; do xmlstarlet val -e -r $(RELAXNG) $$i || exit 1 ; done
	for i in $(UARCHXML) ; do xmlstarlet val -e -r $(UARCHRNG) $$i || exit 1 ; done

generated/%.html: xslt/%.xslt generated/%.xml
	xsltproc -o $@ $^

generated/processorzoo.xml: $(XML)
	echo '<?xml version="1.0"?>' > $@ && \
	echo "<!-- Generated by $(MAKE) $(shell date -R) -->" >> $@ && \
	echo '<processorzoo>' >> $@ && \
	for i in $^ ; do\
	 xmlstarlet sel -t -c //processor $$i >> $@ ; \
	done && \
	echo '</processorzoo>' >> $@

generated/uarches.rng: $(MAKEFILE) $(UARCHXML)
	mkdir -p $(@D)
	echo "<!-- Generated by $(MAKE) $(shell date -R) -->" > $@ && \
	 echo '<grammar xmlns="http://relaxng.org/ns/structure/1.0">' >> $@ && \
	 echo '<define name="uarches">' >> $@ && \
	 echo " <choice>" >> $@ && \
	 for i in $(UARCHXML) ; do \
	  for j in `xmlstarlet sel -t -v //uarch/@name $$i` ; do \
	   echo "  <value>$$j</value>" >> $@ ; \
	  done ; \
	 done && \
	 echo " </choice>" >> $@ && \
	 echo "</define>" >> $@ && \
	 echo "</grammar>" >> $@

# FIXME writes double entries. check for preexisting entry before adding!
generated/isas.rng: $(MAKEFILE) $(UARCHXML)
	mkdir -p $(@D)
	echo "<!-- Generated by $(MAKE) $(shell date -R) -->" > $@ && \
	 echo '<grammar xmlns="http://relaxng.org/ns/structure/1.0">' >> $@ && \
	 echo '<define name="isas">' >> $@ && \
	 echo " <choice>" >> $@ && \
	 for i in $(UARCHXML) ; do \
	  for j in `xmlstarlet sel -t -v //uarch/isa/@name $$i` ; do \
	   echo "  <value>$$j</value>" >> $@ ; \
	  done ; \
	 done && \
	 echo " </choice>" >> $@ && \
	 echo "</define>" >> $@ && \
	 echo "</grammar>" >> $@

clean:
	rm -rf generated
