.DELETE_ON_ERROR:
.PHONY: all validate clean

UARCHRNG:=uarch.rng
RELAXNG:=processorzoo.rng
XML:=$(wildcard *.xml)
LISTS:=$(addprefix generated/,uarches.rng)
UARCHXML:=$(wildcard uarches/*.xml)

all: validate

validate: $(UARCHRNG) $(RELAXNG) $(XML) $(LISTS)
	for i in $(XML) ; do xmlstarlet val -e -r $(RELAXNG) $$i ; done
	for i in $(UARCHXML) ; do xmlstarlet val -e -r $(UARCHRNG) $$i ; done

generated/uarches.rng: $(MAKEFILE) $(UARCHXML)
	mkdir -p $(@D)
	echo "<!-- Generated by $(MAKE) $(shell date -R) -->" > $@ && \
	 echo '<grammar xmlns="http://relaxng.org/ns/structure/1.0">' >> $@ && \
	 echo '<define name="uarches">' >> $@ && \
	 echo " <choice>" >> $@ && \
	 for i in $(UARCHXML) ; do \
	  echo -n "  <value>" >> $@ && \
	  xmlstarlet sel -t -v //uarch/@name $$i >> $@ && \
	  echo "</value>" >> $@ ; done && \
	 echo " </choice>" >> $@ && \
	 echo "</define>" >> $@ && \
	 echo "</grammar>" >> $@

clean:
	rm -rf generated
